Add `SharedKeys::disableCaching`
couchbaselabs/fleece pull request #177
Opened 2023-05-22 18:17 UTC by blaugold

@snej Thanks for the advice in https://github.com/couchbase/couchbase-lite-core/pull/1642#issuecomment-1536548762. This 
 PR is implementing the suggested changes.

2023-06-22 22:14 UTC, jianminzhao requested changes

2023-06-22 22:14 UTC, jianminzhao commented on Fleece/Core/SharedKeys.hh
> +        bool _isCacheable {true};
Why do you need two of the above?

2023-06-22 22:14 UTC, jianminzhao commented on Tests/SharedKeysTests.cc
> +    sk->disableCaching();
Whereas we want to ensure diableCaching does not affect the following checks, the other aspect is ensure get(Dict::key &keyToFind) works as expected.

2023-07-17 18:58 UTC, jianminzhao commented
@blaugold are you still interested in moving forward? If not, I am going to close it.

2023-07-18 06:25 UTC, blaugold commented
@jianminzhao Thanks for reviewing this PR! I still want to work on this, I just haven't had time to respond yet. I hope I can get to it this week.

2023-09-11 16:20 UTC, closed without merging