API: Added FLSlot_SetArray, FLSlot_SetDict
couchbaselabs/fleece pull request #93
Opened 2021-03-31 00:25 UTC by snej

Simple inlines to avoid having to cast to (FLValue)

2021-03-31 00:45 UTC, borrrden requested changes
Could we have the mutable variants too? :)

2021-03-31 00:45 UTC, borrrden commented on API/fleece/Fleece.h
> +    static inline void FLSlot_SetArray(FLSlot NONNULL slot, FLArray array) {
I wonder if array should be non-null.  Would a null array be a shortcut for `SetNull` ?

2021-04-19 23:32 UTC, borrrden commented
Does #95 supersede this?

2021-04-19 23:48 UTC, snej commented
> Could we have the mutable variants too? :)

`FLMutableArray` is just a non-const `FLArray`, so they're type compatible already.

2021-04-19 23:48 UTC, snej commented
> Does #95 supersede this?

No, it just means more inlines for me to write...

2021-04-22 00:41 UTC, borrrden approved these changes

2021-05-06 23:28 UTC, merged